name: SIRS-genomics
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - async-lru=2.0.2
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - comm=0.1.3
  - cryptography=40.0.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - flit-core=3.9.0
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - ipykernel=6.23.1
  - ipython=8.13.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter-lsp=2.1.0
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.1
  - jupyterlab_widgets=3.0.7
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - nbclassic=1.0.0
  - nbclient=0.7.4
  - nbconvert-core=7.4.0
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numpy=1.24.3
  - openssl=3.1.0
  - packaging=23.1
  - pandas=2.0.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.1
  - plotly=5.14.1
  - pooch=1.7.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.1.1
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.0.2
  - readline=8.2
  - requests=2.29.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - send2trash=1.8.2
  - setuptools=67.7.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - tenacity=8.2.2
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
